backend:
  name: github
  repo: Hubackova/muni-hydroweb

media_folder: static/images
public_folder: images

collections:
  - name: "people"
    label: "People"
    folder: "src/pages/people"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Thesis", name: "thesis", widget: "string"}
      - {label: "Supervisor", name: "supervisor", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Phone", name: "phone", widget: "number"}
      - {label: "Room", name: "room", widget: "string"}
      - {label: "IS", name: "is", widget: "string"}
      - {label: "RG", name: "rg", widget: "string"}
      - {label: 'Image', name: 'image', widget: 'image' }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: pages
    label: Pages
    files:
      - file: "src/pages/courses/courses-2.md"
        label: "Courses 2"
        name: "courses-2"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/courses/courses.md"
        label: "Courses"
        name: "courses"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}